# 配置数据库连接三要素：连接地址、账户、密码
# 连接地址：由Spring框架提供的数据库连接地址数据源，底层调用JDBC技术；配置格式固定
# /// 是 //localhost:3306/ 简写；serverTimezone=GMT%2B8 -- GMT+8
spring.datasource.url=jdbc:mysql:///rbac?serverTimezone=GMT%2B8&characterEncoding=utf8&useUnicode=true&characterSetResults=utf8
# 数据库连接账户名
spring.datasource.username=root
# 数据库root账户的密码 -- 写你自己数据库的密码
spring.datasource.password=root

# 配置MyBatis框架扫描器：主要用于配置指定类型别名的扫描包（当前为注释状态：未启用）
# mybatis.type-aliases-package=cn.wolfcode.domain

# 配置日志级别，设置cn.wolfcode.mapper包下的日志级别为trace，用于在控制台打印该包下指定的SQL语句
logging.level.cn.wolfcode.mapper=trace

# 配置Spring AOP面向切面编程思想是否使用CGLIB动态代理类（当前为注释状态：未启用，通常默认为true）
# spring.aop.proxy-target-class=false

# 修改服务器端口号为80（默认Tomcat服务器端口号为8080，为了防止已有项目冲突）
server.port=81

# 通过SpringMVC框架配置解析前端静态Web资源路径前缀/static/**，即访问静态资源必须以/static开头，**表示识别所有
# 演示静态Web资源路径：CSS文件 -- /static/css/a.css
# 演示静态Web资源路径：JS文件 -- /static/js/a.js
# 演示静态Web资源路径：HTML文件 -- /static/html/a.html
# 注意！！！后续项目中会配置拦截器；如果放行上述的静态Web资源，可以直接配置过滤路径为/static/**
spring.mvc.static-path-pattern=/static/**

# 基于Spring框架配置Thymeleaf模板引擎关闭缓存（开发环境下常用；避免修改模板后重启服务），默认是true，即开启
spring.thymeleaf.cache=false

# 配置Pagehelper分页插件，开启合理化分页（即页码超出范围时自动处理）
pagehelper.reasonable=true

# 配置Pagehelper分页插件，允许页数为0情况（即查询第0页时返回空数据，而非报错）
pagehelper.page-size-zero=true

# 配置Spring Boot自动执行SQL脚本
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=true